import * as fs from 'fs';
import * as path from 'path';

const seedMenuPath = path.join(__dirname, 'seed-menu.ts');

const content = `import prisma from './database/prisma';

async function main() {
  console.log('Starting comprehensive menu seeding...');

  // --- Category Upserts ---
  const hotCoffeeCat = await prisma.category.upsert({
    where: { id: 'cat-hot-coffee' },
    update: {},
    create: {
      id: 'cat-hot-coffee',
      name: 'Hot Coffee',
      slug: 'hot-coffee',
      description: 'Freshly brewed hot espresso and coffee drinks.',
      image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=3840&q=100',
      isActive: true,
      sortOrder: 1,
    },
  });

  const coldCoffeeCat = await prisma.category.upsert({
    where: { id: 'cat-cold-coffee' },
    update: {},
    create: {
      id: 'cat-cold-coffee',
      name: 'Cold Coffee & Brews',
      slug: 'cold-coffee-brews',
      description: 'Refreshing iced coffees and slow-steeped cold brews.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=3840&q=100',
      isActive: true,
      sortOrder: 2,
    },
  });

  const dessertsCat = await prisma.category.upsert({
    where: { id: 'cat-desserts' },
    update: {},
    create: {
      id: 'cat-desserts',
      name: 'Desserts',
      slug: 'desserts',
      description: 'Delicious desserts, cheesecakes, pastries, and cakes.',
      image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=3840&q=100',
      isActive: true,
      sortOrder: 3,
    },
  });

  const iceCreamCat = await prisma.category.upsert({
    where: { id: 'cat-ice-cream' },
    update: {},
    create: {
      id: 'cat-ice-cream',
      name: 'Ice Creams',
      slug: 'ice-creams',
      description: 'Rich, creamy and delightful ice creams.',
      image: 'https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100',
      isActive: true,
      sortOrder: 4,
    },
  });

  const sandwichCat = await prisma.category.upsert({
    where: { id: 'cat-sandwiches' },
    update: {},
    create: {
      id: 'cat-sandwiches',
      name: 'Sandwiches',
      slug: 'sandwiches',
      description: 'Freshly toasted and grilled sandwiches.',
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=3840&q=100',
      isActive: true,
      sortOrder: 5,
    },
  });

  const mocktailCat = await prisma.category.upsert({
    where: { id: 'cat-mocktails' },
    update: {},
    create: {
      id: 'cat-mocktails',
      name: 'Mocktails',
      slug: 'mocktails',
      description: 'Refreshing and vibrant non-alcoholic mocktails.',
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=3840&q=100',
      isActive: true,
      sortOrder: 6,
    },
  });

  const products = [
    // ==========================================
    // 1. HOT COFFEE (13 items)
    // ==========================================
    {
      id: 'hc-1',
      name: 'Espresso',
      slug: 'espresso',
      description: 'Strong coffee shot, base coffee.',
      shortDesc: 'Strong coffee shot.',
      price: 80,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.8,
      reviewCount: 95,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'hc-2',
      name: 'Americano',
      slug: 'americano',
      description: 'Espresso + garam pani.',
      shortDesc: 'Espresso diluted with hot water.',
      price: 95,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1551030173-1d2056c14725?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.5,
      reviewCount: 42,
      isActive: true,
    },
    {
      id: 'hc-3',
      name: 'Cappuccino',
      slug: 'cappuccino',
      description: 'Espresso + steamed milk + milk foam.',
      shortDesc: 'Espresso with steamed milk and thick foam.',
      price: 110,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570968915860-54d5c301fc9f?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.7,
      reviewCount: 88,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'hc-4',
      name: 'Latte',
      slug: 'latte',
      description: 'Espresso + jast steamed milk + thodi foam.',
      shortDesc: 'Espresso with lots of steamed milk and light foam.',
      price: 115,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1541167760496-1628856ab772?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.6,
      reviewCount: 75,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'hc-5',
      name: 'Flat White',
      slug: 'flat-white',
      description: 'Espresso + silky steamed milk.',
      shortDesc: 'Double espresso with velvety microfoam.',
      price: 120,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.8,
      reviewCount: 52,
      isActive: true,
    },
    {
      id: 'hc-6',
      name: 'Mocha',
      slug: 'mocha',
      description: 'Espresso + chocolate + milk.',
      shortDesc: 'Espresso with rich chocolate and steamed milk.',
      price: 130,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.7,
      reviewCount: 63,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'hc-7',
      name: 'Macchiato',
      slug: 'macchiato',
      description: 'Espresso var thodi milk foam.',
      shortDesc: 'Espresso marked with a dollop of foam.',
      price: 100,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.4,
      reviewCount: 31,
      isActive: true,
    },
    {
      id: 'hc-8',
      name: 'Cortado',
      slug: 'cortado',
      description: 'Espresso ani milk saman pramanat.',
      shortDesc: 'Equal parts espresso and warm milk.',
      price: 105,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1534778101976-62847782c213?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.6,
      reviewCount: 29,
      isActive: true,
    },
    {
      id: 'hc-9',
      name: 'Irish Coffee',
      slug: 'irish-coffee',
      description: 'Coffee + cream (paramparik recipe madhye alcohol asto).',
      shortDesc: 'Hot coffee combined with cream.',
      price: 150,
      stock: 50,
      images: ['https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.8,
      reviewCount: 40,
      isActive: true,
    },
    {
      id: 'hc-10',
      name: 'Affogato',
      slug: 'affogato',
      description: 'Garam espresso vanilla ice cream var.',
      shortDesc: 'A scoop of vanilla ice cream drowned in hot espresso.',
      price: 140,
      stock: 60,
      images: ['https://images.unsplash.com/photo-1594911774802-8822a707caff?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.9,
      reviewCount: 78,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'hc-11',
      name: 'Filter Coffee',
      slug: 'filter-coffee',
      description: 'South Indian style filter coffee.',
      shortDesc: 'Traditional aromatic frothy filter coffee.',
      price: 70,
      stock: 120,
      images: ['https://images.unsplash.com/photo-1608228088998-57828365d486?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.9,
      reviewCount: 110,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'hc-12',
      name: 'Turkish Coffee',
      slug: 'turkish-coffee',
      description: 'Khup fine coffee powder pasun banavtat.',
      shortDesc: 'Thick, strong traditional Turkish coffee.',
      price: 120,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.7,
      reviewCount: 35,
      isActive: true,
    },
    {
      id: 'hc-13',
      name: 'Black Coffee',
      slug: 'black-coffee',
      description: 'Dudh shivay coffee.',
      shortDesc: 'Pure hot black coffee without milk.',
      price: 60,
      stock: 150,
      images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=3840&q=100'],
      categoryId: hotCoffeeCat.id,
      rating: 4.5,
      reviewCount: 65,
      isActive: true,
    },

    // ==========================================
    // 2. COLD COFFEE & BREWS (13 items)
    // ==========================================
    {
      id: 'cc-1',
      name: 'Classic Cold Coffee',
      slug: 'classic-cold-coffee',
      description: 'Coffee + milk + ice.',
      shortDesc: 'Classic chilled cold coffee.',
      price: 90,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.6,
      reviewCount: 80,
      isActive: true,
    },
    {
      id: 'cc-2',
      name: 'Cold Coffee with Ice Cream',
      slug: 'cold-coffee-with-ice-cream',
      description: 'Vanilla ice cream sobat.',
      shortDesc: 'Cold coffee served with a scoop of vanilla ice cream.',
      price: 110,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1541167760496-1628856ab772?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.8,
      reviewCount: 95,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'cc-3',
      name: 'Chocolate Cold Coffee',
      slug: 'chocolate-cold-coffee',
      description: 'Chocolate flavor.',
      shortDesc: 'Delicious cold coffee with rich chocolate flavor.',
      price: 100,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.7,
      reviewCount: 60,
      isActive: true,
    },
    {
      id: 'cc-4',
      name: 'Mocha Cold Coffee',
      slug: 'mocha-cold-coffee',
      description: 'Coffee + chocolate mix.',
      shortDesc: 'Chilled mocha blended with rich chocolate and espresso.',
      price: 110,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.6,
      reviewCount: 45,
      isActive: true,
    },
    {
      id: 'cc-5',
      name: 'Caramel Cold Coffee',
      slug: 'caramel-cold-coffee',
      description: 'Caramel syrup sobat.',
      shortDesc: 'Cold coffee blended with sweet caramel syrup.',
      price: 110,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.7,
      reviewCount: 70,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'cc-6',
      name: 'Hazelnut Cold Coffee',
      slug: 'hazelnut-cold-coffee',
      description: 'Hazelnut flavor.',
      shortDesc: 'Cold coffee infused with nutty hazelnut flavor.',
      price: 110,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.8,
      reviewCount: 88,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'cc-7',
      name: 'Vanilla Cold Coffee',
      slug: 'vanilla-cold-coffee',
      description: 'Vanilla flavored.',
      shortDesc: 'Sweet and creamy vanilla flavored cold coffee.',
      price: 100,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1551030173-1d2056c14725?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.5,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'cc-8',
      name: 'Oreo Cold Coffee',
      slug: 'oreo-cold-coffee',
      description: 'Oreo biscuits blend kelele.',
      shortDesc: 'Thick shake style cold coffee blended with Oreo biscuits.',
      price: 120,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.9,
      reviewCount: 120,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'cc-9',
      name: 'KitKat Cold Coffee',
      slug: 'kitkat-cold-coffee',
      description: 'KitKat flavor.',
      shortDesc: 'Cold coffee blended with crispy KitKat chocolate bars.',
      price: 125,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1587314168485-3236d6710814?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.8,
      reviewCount: 98,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'cc-10',
      name: 'Irish Cold Coffee',
      slug: 'irish-cold-coffee',
      description: 'Irish cream flavor (non-alcoholic version available).',
      shortDesc: 'Chilled coffee with smooth Irish cream flavor.',
      price: 130,
      stock: 60,
      images: ['https://images.unsplash.com/photo-1534778101976-62847782c213?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.6,
      reviewCount: 35,
      isActive: true,
    },
    {
      id: 'cb-1',
      name: 'Classic Cold Brew',
      slug: 'classic-cold-brew',
      description: 'Steeped for 18 hours for maximum smoothness.',
      shortDesc: '18-hour slow steeped cold brew.',
      price: 110,
      stock: 50,
      images: ['https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.7,
      reviewCount: 40,
      isActive: true,
    },
    {
      id: 'cb-2',
      name: 'Vanilla Cold Brew',
      slug: 'vanilla-cold-brew',
      description: 'Slow steeped cold brew infused with sweet vanilla.',
      shortDesc: 'Vanilla infused smooth cold brew.',
      price: 120,
      stock: 50,
      images: ['https://images.unsplash.com/photo-1541167760496-1628856ab772?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.6,
      reviewCount: 22,
      isActive: true,
    },
    {
      id: 'cb-3',
      name: 'Caramel Cold Brew',
      slug: 'caramel-cold-brew',
      description: 'Slow steeped cold brew with a swirl of caramel syrup.',
      shortDesc: 'Caramel infused smooth cold brew.',
      price: 125,
      stock: 50,
      images: ['https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=3840&q=100'],
      categoryId: coldCoffeeCat.id,
      rating: 4.8,
      reviewCount: 33,
      isActive: true,
      isBestseller: true,
    },

    // ==========================================
    // 3. DESSERTS (25 items)
    // ==========================================
    {
      id: 'de-1',
      name: 'New York Cheesecake',
      slug: 'new-york-cheesecake',
      description: 'Classic dense and creamy New York style cheesecake.',
      shortDesc: 'Classic New York style cheesecake.',
      price: 180,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.8,
      reviewCount: 50,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'de-2',
      name: 'Blueberry Cheesecake',
      slug: 'blueberry-cheesecake',
      description: 'Cheesecake topped with sweet blueberry compote.',
      shortDesc: 'Blueberry topped creamy cheesecake.',
      price: 190,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1524351199679-46cddf530c04?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.9,
      reviewCount: 65,
      isActive: true,
    },
    {
      id: 'de-3',
      name: 'Lotus Biscoff Cheesecake',
      slug: 'lotus-biscoff-cheesecake',
      description: 'Creamy cheesecake blended and topped with Lotus Biscoff spread and crumbs.',
      shortDesc: 'Decadent Lotus Biscoff cheesecake.',
      price: 210,
      stock: 12,
      images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.9,
      reviewCount: 75,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'de-4',
      name: 'Chocolate Cheesecake',
      slug: 'chocolate-cheesecake',
      description: 'Rich chocolate cheesecake for true chocolate lovers.',
      shortDesc: 'Creamy and rich chocolate cheesecake.',
      price: 185,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.7,
      reviewCount: 40,
      isActive: true,
    },
    {
      id: 'de-5',
      name: 'Classic Chocolate Brownie',
      slug: 'classic-chocolate-brownie',
      description: 'Fudgy and rich chocolate brownie.',
      shortDesc: 'Rich and fudgy classic chocolate brownie.',
      price: 90,
      stock: 30,
      images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.6,
      reviewCount: 55,
      isActive: true,
    },
    {
      id: 'de-6',
      name: 'Walnut Brownie',
      slug: 'walnut-brownie',
      description: 'Fudgy chocolate brownie packed with crunchy walnuts.',
      shortDesc: 'Classic chocolate walnut brownie.',
      price: 100,
      stock: 25,
      images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.7,
      reviewCount: 42,
      isActive: true,
    },
    {
      id: 'de-7',
      name: 'Brownie with Ice Cream',
      slug: 'brownie-with-ice-cream',
      description: 'Warm chocolate brownie served with a scoop of vanilla ice cream and chocolate drizzle.',
      shortDesc: 'Warm brownie with vanilla ice cream.',
      price: 130,
      stock: 30,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.9,
      reviewCount: 110,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'de-8',
      name: 'Choco Lava Brownie',
      slug: 'choco-lava-brownie',
      description: 'Warm brownie with a gooey molten chocolate center.',
      shortDesc: 'Molten chocolate center brownie.',
      price: 110,
      stock: 25,
      images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.8,
      reviewCount: 88,
      isActive: true,
    },
    {
      id: 'de-9',
      name: 'Black Forest Pastry',
      slug: 'black-forest-pastry',
      description: 'Layers of chocolate sponge, whipped cream, and cherries.',
      shortDesc: 'Classic Black Forest pastry.',
      price: 75,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.4,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'de-10',
      name: 'Chocolate Truffle Pastry',
      slug: 'chocolate-truffle-pastry',
      description: 'Decadent chocolate sponge layered with rich truffle ganache.',
      shortDesc: 'Rich chocolate truffle pastry.',
      price: 85,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.7,
      reviewCount: 48,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'de-11',
      name: 'Red Velvet Pastry',
      slug: 'red-velvet-pastry',
      description: 'Vibrant red velvet sponge layered with cream cheese frosting.',
      shortDesc: 'Creamy red velvet pastry.',
      price: 90,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1586985289688-ca9cf499150a?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.6,
      reviewCount: 35,
      isActive: true,
    },
    {
      id: 'de-12',
      name: 'Butterscotch Pastry',
      slug: 'butterscotch-pastry',
      description: 'Caramelized butterscotch cream with crunchy praline.',
      shortDesc: 'Sweet butterscotch pastry.',
      price: 75,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.3,
      reviewCount: 22,
      isActive: true,
    },
    {
      id: 'de-13',
      name: 'Chocolate Cake',
      slug: 'chocolate-cake',
      description: 'Whole classic chocolate celebration cake.',
      shortDesc: 'Classic chocolate celebration cake.',
      price: 450,
      stock: 10,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.7,
      reviewCount: 38,
      isActive: true,
    },
    {
      id: 'de-14',
      name: 'Red Velvet Cake',
      slug: 'red-velvet-cake',
      description: 'Whole rich red velvet cake with cream cheese layers.',
      shortDesc: 'Whole red velvet cream cheese cake.',
      price: 550,
      stock: 8,
      images: ['https://images.unsplash.com/photo-1586985289688-ca9cf499150a?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.8,
      reviewCount: 25,
      isActive: true,
    },
    {
      id: 'de-15',
      name: 'Dutch Truffle Cake',
      slug: 'dutch-truffle-cake',
      description: 'Indulgent Dutch chocolate truffle cake.',
      shortDesc: 'Indulgent Dutch truffle cake.',
      price: 500,
      stock: 10,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.9,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'de-16',
      name: 'Fruit Cake',
      slug: 'fruit-cake',
      description: 'Fresh seasonal fruit cake with vanilla whipped cream.',
      shortDesc: 'Fresh seasonal fruit cake.',
      price: 480,
      stock: 6,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.5,
      reviewCount: 15,
      isActive: true,
    },
    {
      id: 'de-17',
      name: 'Tiramisu',
      slug: 'tiramisu',
      description: 'Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone.',
      shortDesc: 'Classic Italian coffee dessert.',
      price: 160,
      stock: 12,
      images: ['https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.9,
      reviewCount: 62,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'de-18',
      name: 'Chocolate Mousse',
      slug: 'chocolate-mousse',
      description: 'Light and airy whipped chocolate mousse.',
      shortDesc: 'Light whipped chocolate mousse.',
      price: 110,
      stock: 18,
      images: ['https://images.unsplash.com/photo-1541795795328-f073b763494e?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.6,
      reviewCount: 28,
      isActive: true,
    },
    {
      id: 'de-19',
      name: 'Lotus Biscoff Jar',
      slug: 'lotus-biscoff-jar',
      description: 'Layered dessert jar with biscoff cheesecake, spread and biscuits.',
      shortDesc: 'Cheesecake jar with Lotus Biscoff.',
      price: 140,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.8,
      reviewCount: 45,
      isActive: true,
    },
    {
      id: 'de-20',
      name: 'Oreo Jar Cake',
      slug: 'oreo-jar-cake',
      description: 'Layered Oreo cookies and white cream in a dessert jar.',
      shortDesc: 'Cookies and cream dessert jar.',
      price: 120,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.7,
      reviewCount: 38,
      isActive: true,
    },
    {
      id: 'de-21',
      name: 'Belgian Chocolate Jar Cake',
      slug: 'belgian-chocolate-jar-cake',
      description: 'Layers of rich Belgian chocolate sponge and ganache in a jar.',
      shortDesc: 'Rich Belgian chocolate jar.',
      price: 140,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.9,
      reviewCount: 50,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'de-22',
      name: 'Gulab Jamun with Ice Cream',
      slug: 'gulab-jamun-with-ice-cream',
      description: 'Hot, sweet gulab jamuns served with cold vanilla ice cream.',
      shortDesc: 'Hot gulab jamun with vanilla ice cream.',
      price: 100,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.8,
      reviewCount: 90,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'de-23',
      name: 'Rabdi',
      slug: 'rabdi',
      description: 'Sweet, condensed-milk dish layered with malai.',
      shortDesc: 'Traditional sweet condensed milk.',
      price: 80,
      stock: 30,
      images: ['https://images.unsplash.com/photo-1608228088998-57828365d486?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.7,
      reviewCount: 32,
      isActive: true,
    },
    {
      id: 'de-24',
      name: 'Shrikhand',
      slug: 'shrikhand',
      description: 'Traditional sweet yogurt dessert flavored with cardamom and saffron.',
      shortDesc: 'Traditional sweet yogurt dessert.',
      price: 70,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1608228088998-57828365d486?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.6,
      reviewCount: 25,
      isActive: true,
    },
    {
      id: 'de-25',
      name: 'Kulfi',
      slug: 'kulfi',
      description: 'Traditional Indian frozen dessert made with rich condensed milk.',
      shortDesc: 'Traditional Indian frozen kulfi.',
      price: 60,
      stock: 50,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: dessertsCat.id,
      rating: 4.8,
      reviewCount: 55,
      isActive: true,
    },

    // ==========================================
    // 4. ICE CREAMS (27 items)
    // ==========================================
    {
      id: 'ic-1',
      name: 'Vanilla Ice Cream',
      slug: 'vanilla-ice-cream',
      description: 'Classic creamy vanilla ice cream.',
      shortDesc: 'Classic creamy vanilla.',
      price: 50,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.4,
      reviewCount: 35,
      isActive: true,
    },
    {
      id: 'ic-2',
      name: 'Chocolate Ice Cream',
      slug: 'chocolate-ice-cream',
      description: 'Rich and dark chocolate ice cream.',
      shortDesc: 'Rich and dark chocolate flavor.',
      price: 60,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.6,
      reviewCount: 50,
      isActive: true,
    },
    {
      id: 'ic-3',
      name: 'Strawberry Ice Cream',
      slug: 'strawberry-ice-cream',
      description: 'Sweet strawberry ice cream with fruit bits.',
      shortDesc: 'Sweet strawberry flavor.',
      price: 60,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.5,
      reviewCount: 28,
      isActive: true,
    },
    {
      id: 'ic-4',
      name: 'Butterscotch Ice Cream',
      slug: 'butterscotch-ice-cream',
      description: 'Sweet butterscotch flavor with crunchy praline.',
      shortDesc: 'Butterscotch with praline crunch.',
      price: 60,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.7,
      reviewCount: 42,
      isActive: true,
    },
    {
      id: 'ic-5',
      name: 'Mango Ice Cream',
      slug: 'mango-ice-cream',
      description: 'Tropical Alphonso mango flavored ice cream.',
      shortDesc: 'Alphonso mango flavor.',
      price: 60,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.6,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'ic-6',
      name: 'Kesar Pista Ice Cream',
      slug: 'kesar-pista-ice-cream',
      description: 'Traditional saffron and pistachio flavor.',
      shortDesc: 'Saffron and pistachio flavor.',
      price: 70,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.8,
      reviewCount: 55,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'ic-7',
      name: 'Black Currant Ice Cream',
      slug: 'black-currant-ice-cream',
      description: 'Tangy black currant ice cream with dried berries.',
      shortDesc: 'Tangy black currant flavor.',
      price: 70,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.5,
      reviewCount: 22,
      isActive: true,
    },
    {
      id: 'ic-8',
      name: 'Coffee Ice Cream',
      slug: 'coffee-ice-cream',
      description: 'Rich coffee kick in creamy ice cream.',
      shortDesc: 'Rich coffee flavored ice cream.',
      price: 65,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.6,
      reviewCount: 31,
      isActive: true,
    },
    {
      id: 'ic-9',
      name: 'Belgian Chocolate Ice Cream',
      slug: 'belgian-chocolate-ice-cream',
      description: 'Intense and rich premium Belgian dark chocolate ice cream.',
      shortDesc: 'Premium Belgian dark chocolate.',
      price: 90,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.9,
      reviewCount: 85,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'ic-10',
      name: 'Lotus Biscoff Ice Cream',
      slug: 'lotus-biscoff-ice-cream',
      description: 'Creamy speculoos cookie butter ice cream with biscoff swirl.',
      shortDesc: 'Speculoos cookie butter ice cream.',
      price: 100,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.9,
      reviewCount: 78,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'ic-11',
      name: 'Ferrero Rocher Ice Cream',
      slug: 'ferrero-rocher-ice-cream',
      description: 'Hazelnut and chocolate blended ice cream with Ferrero Rocher bits.',
      shortDesc: 'Hazelnut chocolate Ferrero flavor.',
      price: 110,
      stock: 60,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.9,
      reviewCount: 92,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'ic-12',
      name: 'Cookies & Cream Ice Cream',
      slug: 'cookies-cream-ice-cream',
      description: 'Creamy vanilla base with crushed chocolate sandwich cookies.',
      shortDesc: 'Vanilla with crushed chocolate cookies.',
      price: 85,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.7,
      reviewCount: 45,
      isActive: true,
    },
    {
      id: 'ic-13',
      name: 'Red Velvet Ice Cream',
      slug: 'red-velvet-ice-cream',
      description: 'Rich red velvet cake pieces in cream cheese flavored ice cream.',
      shortDesc: 'Red velvet and cream cheese flavor.',
      price: 90,
      stock: 70,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.6,
      reviewCount: 38,
      isActive: true,
    },
    {
      id: 'ic-14',
      name: 'Salted Caramel Ice Cream',
      slug: 'salted-caramel-ice-cream',
      description: 'Perfect blend of sweet caramel and sea salt.',
      shortDesc: 'Sweet and salty caramel.',
      price: 85,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.8,
      reviewCount: 56,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'ic-15',
      name: 'Nutella Ice Cream',
      slug: 'nutella-ice-cream',
      description: 'Creamy chocolate hazelnut Nutella ice cream.',
      shortDesc: 'Rich Nutella chocolate hazelnut.',
      price: 95,
      stock: 80,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.9,
      reviewCount: 104,
      isActive: true,
      isBestseller: true,
    },
    {
      id: 'ic-16',
      name: 'Tender Coconut Ice Cream',
      slug: 'tender-coconut-ice-cream',
      description: 'Refreshing ice cream made with real tender coconut pieces.',
      shortDesc: 'Refreshing tender coconut pieces.',
      price: 85,
      stock: 70,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.7,
      reviewCount: 42,
      isActive: true,
    },
    {
      id: 'ic-17',
      name: 'Chocolate Sundae',
      slug: 'chocolate-sundae',
      description: 'Chocolate ice cream scoops topped with hot fudge, whipped cream, and chocolate chips.',
      shortDesc: 'Indulgent chocolate sundae.',
      price: 130,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.7,
      reviewCount: 48,
      isActive: true,
    },
    {
      id: 'ic-18',
      name: 'Brownie Sundae',
      slug: 'brownie-sundae',
      description: 'Warm brownie base topped with vanilla scoops, chocolate fudge, and nuts.',
      shortDesc: 'Warm brownie and vanilla sundae.',
      price: 150,
      stock: 45,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.9,
      reviewCount: 130,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'ic-19',
      name: 'Oreo Sundae',
      slug: 'oreo-sundae',
      description: 'Vanilla scoops layered with crushed Oreo cookies and chocolate syrup.',
      shortDesc: 'Vanilla and Oreo cookies sundae.',
      price: 130,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.8,
      reviewCount: 64,
      isActive: true,
    },
    {
      id: 'ic-20',
      name: 'Hot Fudge Sundae',
      slug: 'hot-fudge-sundae',
      description: 'Vanilla ice cream with warm hot fudge sauce, nuts, and a cherry.',
      shortDesc: 'Classic hot fudge sundae.',
      price: 135,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.8,
      reviewCount: 72,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'ic-21',
      name: 'Fruit Sundae',
      slug: 'fruit-sundae',
      description: 'Vanilla and strawberry scoops topped with mixed fruits and fruit syrup.',
      shortDesc: 'Refreshing mixed fruit sundae.',
      price: 140,
      stock: 35,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.6,
      reviewCount: 29,
      isActive: true,
    },
    {
      id: 'ic-22',
      name: 'Single Scoop',
      slug: 'single-scoop',
      description: 'Single scoop of any classic ice cream flavor of your choice.',
      shortDesc: 'Single scoop of classic ice cream.',
      price: 50,
      stock: 200,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.3,
      reviewCount: 40,
      isActive: true,
    },
    {
      id: 'ic-23',
      name: 'Double Scoop',
      slug: 'double-scoop',
      description: 'Double scoop of any classic ice cream flavors of your choice.',
      shortDesc: 'Double scoop of classic ice cream.',
      price: 80,
      stock: 150,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.5,
      reviewCount: 45,
      isActive: true,
    },
    {
      id: 'ic-24',
      name: 'Triple Scoop',
      slug: 'triple-scoop',
      description: 'Triple scoop of any classic ice cream flavors of your choice.',
      shortDesc: 'Triple scoop of classic ice cream.',
      price: 110,
      stock: 100,
      images: ['https://images.unsplash.com/photo-1570197781417-0a8237580532?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.6,
      reviewCount: 24,
      isActive: true,
    },
    {
      id: 'ic-25',
      name: 'Choco Lava with Ice Cream',
      slug: 'choco-lava-with-ice-cream',
      description: 'Hot choco lava cake served with a scoop of cold vanilla ice cream.',
      shortDesc: 'Hot choco lava with cold vanilla ice cream.',
      price: 140,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.9,
      reviewCount: 95,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'ic-26',
      name: 'Ice Cream Float',
      slug: 'ice-cream-float',
      description: 'Fizzy soda or cola served with a scoop of vanilla ice cream.',
      shortDesc: 'Fizzy soda with vanilla scoop.',
      price: 90,
      stock: 60,
      images: ['https://images.unsplash.com/photo-1536935338788-846bb9981813?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.4,
      reviewCount: 18,
      isActive: true,
    },
    {
      id: 'ic-27',
      name: 'Waffle with Ice Cream',
      slug: 'waffle-with-ice-cream',
      description: 'Warm, crispy waffle topped with ice cream and chocolate drizzle.',
      shortDesc: 'Crispy waffle with ice cream.',
      price: 130,
      stock: 35,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.8,
      reviewCount: 68,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'ic-28',
      name: 'Banana Split',
      slug: 'banana-split',
      description: 'Split banana served with scoops of vanilla, chocolate and strawberry, topped with syrup and nuts.',
      shortDesc: 'Three scoops banana split.',
      price: 160,
      stock: 25,
      images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=3840&q=100'],
      categoryId: iceCreamCat.id,
      rating: 4.7,
      reviewCount: 30,
      isActive: true,
    },

    // ==========================================
    // 5. SANDWICHES (28 items)
    // ==========================================
    {
      id: 'sw-1',
      name: 'Veg Grilled Sandwich',
      slug: 'veg-grilled-sandwich',
      description: 'Classic grilled sandwich stuffed with fresh vegetables.',
      shortDesc: 'Classic vegetable grilled sandwich.',
      price: 70,
      stock: 50,
      images: ['/veg-club-sandwich.png'],
      categoryId: sandwichCat.id,
      rating: 4.4,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'sw-2',
      name: 'Veg Cheese Sandwich',
      slug: 'veg-cheese-sandwich',
      description: 'Fresh vegetables with a thick layer of melted cheese.',
      shortDesc: 'Vegetable and cheese sandwich.',
      price: 80,
      stock: 45,
      images: ['/grilled-cheese-tomato.png'],
      categoryId: sandwichCat.id,
      rating: 4.5,
      reviewCount: 32,
      isActive: true,
    },
    {
      id: 'sw-3',
      name: 'Bombay Sandwich',
      slug: 'bombay-sandwich',
      description: 'Fresh cucumber, potato, tomato, and mint chutney in white bread.',
      shortDesc: 'Mint chutney potato street sandwich.',
      price: 75,
      stock: 40,
      images: ['/bombay-masala-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.6,
      reviewCount: 48,
      isActive: true,
    },
    {
      id: 'sw-4',
      name: 'Veg Club Sandwich',
      slug: 'veg-club-sandwich',
      description: 'Classic double-decker veg club sandwich with fresh veggies and cheese.',
      shortDesc: 'Classic double-decker veg club sandwich.',
      price: 120,
      stock: 30,
      images: ['/veg-club-sandwich.png'],
      categoryId: sandwichCat.id,
      rating: 4.6,
      reviewCount: 45,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'sw-5',
      name: 'Corn & Cheese Sandwich',
      slug: 'corn-cheese-sandwich',
      description: 'Delicious blend of sweet corn kernels and melted cheese.',
      shortDesc: 'Sweet corn and cheese sandwich.',
      price: 90,
      stock: 35,
      images: ['/corn-spinach-toastie.png'],
      categoryId: sandwichCat.id,
      rating: 4.8,
      reviewCount: 52,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'sw-6',
      name: 'Paneer Tikka Sandwich',
      slug: 'paneer-tikka-sandwich',
      description: 'Spicy marinated paneer tikka chunks grilled inside crusty bread.',
      shortDesc: 'Spicy paneer tikka sandwich.',
      price: 130,
      stock: 25,
      images: ['https://images.unsplash.com/photo-1509722747041-616f39b57569?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.9,
      reviewCount: 88,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'sw-7',
      name: 'Veggie Delight Sandwich',
      slug: 'veggie-delight-sandwich',
      description: 'Bell peppers, onions, olives, and jalapenos with a creamy dressing.',
      shortDesc: 'Bell peppers, olives and dressing sandwich.',
      price: 95,
      stock: 30,
      images: ['https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.5,
      reviewCount: 15,
      isActive: true,
    },
    {
      id: 'sw-8',
      name: 'Mexican Veg Sandwich',
      slug: 'mexican-veg-sandwich',
      description: 'Spicy beans, salsa, and jalapenos with melted cheese.',
      shortDesc: 'Spicy beans and salsa Mexican sandwich.',
      price: 110,
      stock: 30,
      images: ['https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.7,
      reviewCount: 22,
      isActive: true,
    },
    {
      id: 'sw-9',
      name: 'Special Indori Sandwich',
      slug: 'special-indori-sandwich',
      description: 'Unique sandwich with special Indori spices, sev, and chutney.',
      shortDesc: 'Spicy Indori sev and chutney sandwich.',
      price: 110,
      stock: 45,
      images: ['/bombay-masala-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.9,
      reviewCount: 120,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'sw-10',
      name: 'Indori Cheese Burst Sandwich',
      slug: 'indori-cheese-burst-sandwich',
      description: 'Loaded with a special liquid cheese blend and Indori spices.',
      shortDesc: 'Liquid cheese burst Indori sandwich.',
      price: 140,
      stock: 35,
      images: ['/veg-club-sandwich.png'],
      categoryId: sandwichCat.id,
      rating: 4.9,
      reviewCount: 104,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'sw-11',
      name: 'Indori Masala Sandwich',
      slug: 'indori-masala-sandwich',
      description: 'Spicy potato masala filling flavored with Indori jeeravan masala.',
      shortDesc: 'Jeeravan potato masala sandwich.',
      price: 80,
      stock: 50,
      images: ['/bombay-masala-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.6,
      reviewCount: 42,
      isActive: true,
    },
    {
      id: 'sw-12',
      name: 'Indori Sev Sandwich',
      slug: 'indori-sev-sandwich',
      description: 'Crunchy Indori sev with spicy mint chutney and cheese.',
      shortDesc: 'Sev and mint chutney sandwich.',
      price: 75,
      stock: 55,
      images: ['/chutney-cheese-sandwich.png'],
      categoryId: sandwichCat.id,
      rating: 4.5,
      reviewCount: 38,
      isActive: true,
    },
    {
      id: 'sw-13',
      name: 'Indori Chatpata Sandwich',
      slug: 'indori-chatpata-sandwich',
      description: 'Tangy and spicy chatpata chutney with crispy potato patty.',
      shortDesc: 'Tangy potato chatpata sandwich.',
      price: 85,
      stock: 40,
      images: ['/bombay-masala-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.6,
      reviewCount: 29,
      isActive: true,
    },
    {
      id: 'sw-14',
      name: 'Cheese Grilled Sandwich',
      slug: 'cheese-grilled-sandwich',
      description: 'Classic grilled cheese sandwich with gooey cheddar.',
      shortDesc: 'Classic grilled cheese sandwich.',
      price: 85,
      stock: 60,
      images: ['/grilled-cheese-tomato.png'],
      categoryId: sandwichCat.id,
      rating: 4.4,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'sw-15',
      name: 'Triple Cheese Sandwich',
      slug: 'triple-cheese-sandwich',
      description: 'Mouth-watering blend of mozzarella, cheddar, and processed cheese.',
      shortDesc: 'Three cheese loaded sandwich.',
      price: 130,
      stock: 30,
      images: ['/grilled-cheese-tomato.png'],
      categoryId: sandwichCat.id,
      rating: 4.8,
      reviewCount: 65,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'sw-16',
      name: 'Cheese Corn Sandwich',
      slug: 'cheese-corn-sandwich',
      description: 'Creamy cheese and sweet corn grilled sandwich.',
      shortDesc: 'Cheese and sweet corn sandwich.',
      price: 95,
      stock: 40,
      images: ['/corn-spinach-toastie.png'],
      categoryId: sandwichCat.id,
      rating: 4.7,
      reviewCount: 45,
      isActive: true,
    },
    {
      id: 'sw-17',
      name: 'Cheese Chilli Toast',
      slug: 'cheese-chilli-toast',
      description: 'Open toast topped with green chillies and melted cheese.',
      shortDesc: 'Green chillies cheese open toast.',
      price: 90,
      stock: 40,
      images: ['/grilled-cheese-tomato.png'],
      categoryId: sandwichCat.id,
      rating: 4.7,
      reviewCount: 58,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'sw-18',
      name: 'Paneer Cheese Sandwich',
      slug: 'paneer-cheese-sandwich',
      description: 'Soft paneer chunks layered with cheese slices and grilled.',
      shortDesc: 'Paneer chunks with cheese slices.',
      price: 130,
      stock: 35,
      images: ['https://images.unsplash.com/photo-1509722747041-616f39b57569?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.8,
      reviewCount: 70,
      isActive: true,
    },
    {
      id: 'sw-19',
      name: 'Paneer Peri Peri Sandwich',
      slug: 'paneer-peri-peri-sandwich',
      description: 'Soft paneer tossed in fiery peri peri sauce grilled to perfection.',
      shortDesc: 'Fiery peri peri paneer sandwich.',
      price: 135,
      stock: 30,
      images: ['https://images.unsplash.com/photo-1509722747041-616f39b57569?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.8,
      reviewCount: 62,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'sw-20',
      name: 'Paneer Supreme Sandwich',
      slug: 'paneer-supreme-sandwich',
      description: 'Loaded paneer with bell peppers, olives, corn and cheese.',
      shortDesc: 'Loaded supreme paneer sandwich.',
      price: 145,
      stock: 25,
      images: ['https://images.unsplash.com/photo-1509722747041-616f39b57569?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.7,
      reviewCount: 39,
      isActive: true,
    },
    {
      id: 'sw-21',
      name: 'Avocado Sandwich',
      slug: 'avocado-sandwich',
      description: 'Fresh avocado slices with cucumber, sprouts and garlic herb spread.',
      shortDesc: 'Fresh avocado and cucumber sandwich.',
      price: 180,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.8,
      reviewCount: 45,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'sw-22',
      name: 'Mushroom Cheese Sandwich',
      slug: 'mushroom-cheese-sandwich',
      description: 'Sautéed mushrooms with gooey mozzarella cheese.',
      shortDesc: 'Mushroom and mozzarella grilled sandwich.',
      price: 140,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1528736235302-52922df5c122?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.7,
      reviewCount: 28,
      isActive: true,
    },
    {
      id: 'sw-23',
      name: 'Mediterranean Sandwich',
      slug: 'mediterranean-sandwich',
      description: 'Hummus, olives, bell peppers and feta cheese on focaccia.',
      shortDesc: 'Hummus, olives, and feta on focaccia.',
      price: 160,
      stock: 15,
      images: ['https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.6,
      reviewCount: 18,
      isActive: true,
    },
    {
      id: 'sw-24',
      name: 'Mexican Fiesta Sandwich',
      slug: 'mexican-fiesta-sandwich',
      description: 'Spicy salsa, black beans, corn, jalapenos and nachos for crunch.',
      shortDesc: 'Spicy Mexican filling with nachos crunch.',
      price: 135,
      stock: 20,
      images: ['https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=3840&q=100'],
      categoryId: sandwichCat.id,
      rating: 4.5,
      reviewCount: 12,
      isActive: true,
    },
    {
      id: 'sw-25',
      name: 'Chocolate Sandwich',
      slug: 'chocolate-sandwich',
      description: 'Toasted sandwich loaded with melted chocolate chips.',
      shortDesc: 'Toasted sweet chocolate sandwich.',
      price: 110,
      stock: 30,
      images: ['/chocolate-banana-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.6,
      reviewCount: 35,
      isActive: true,
    },
    {
      id: 'sw-26',
      name: 'Nutella Sandwich',
      slug: 'nutella-sandwich',
      description: 'Sweet sandwich filled with hazelnut chocolate spread.',
      shortDesc: 'Hazelnut chocolate spread toast.',
      price: 120,
      stock: 40,
      images: ['/chocolate-banana-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.9,
      reviewCount: 115,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'sw-27',
      name: 'Chocolate Cheese Sandwich',
      slug: 'chocolate-cheese-sandwich',
      description: 'Surprising combination of sweet chocolate and melted cheese.',
      shortDesc: 'Sweet chocolate and cheese sandwich.',
      price: 120,
      stock: 25,
      images: ['/chocolate-banana-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.4,
      reviewCount: 15,
      isActive: true,
    },
    {
      id: 'sw-28',
      name: 'Oreo Chocolate Sandwich',
      slug: 'oreo-chocolate-sandwich',
      description: 'Crushed Oreo cookies and warm chocolate spread.',
      shortDesc: 'Crushed Oreos and chocolate spread.',
      price: 125,
      stock: 30,
      images: ['/chocolate-banana-toast.png'],
      categoryId: sandwichCat.id,
      rating: 4.7,
      reviewCount: 44,
      isActive: true,
    },

    // ==========================================
    // 6. MOCKTAILS (24 items)
    // ==========================================
    {
      id: 'mc-1',
      name: 'Virgin Mojito',
      slug: 'virgin-mojito',
      description: 'Refreshing blend of fresh mint, lime juice, sugar, and sparkling soda.',
      shortDesc: 'Refreshing mint and lime cooler.',
      price: 90,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.7,
      reviewCount: 35,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'mc-2',
      name: 'Blue Lagoon',
      slug: 'blue-lagoon',
      description: 'Vibrant blue mocktail with blue curacao, lime, and sprite.',
      shortDesc: 'Vibrant blue curacao soda cooler.',
      price: 100,
      stock: 50,
      images: ['/blue-lagoon.png'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 28,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'mc-3',
      name: 'Green Apple Mojito',
      slug: 'green-apple-mojito',
      description: 'Crisp green apple syrup muddled with mint, lime and club soda.',
      shortDesc: 'Crisp green apple syrup mojito.',
      price: 110,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.7,
      reviewCount: 45,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'mc-4',
      name: 'Watermelon Mojito',
      slug: 'watermelon-mojito',
      description: 'Sweet fresh watermelon juice with mint, lime and soda.',
      shortDesc: 'Fresh watermelon mint cooler.',
      price: 110,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 33,
      isActive: true,
    },
    {
      id: 'mc-5',
      name: 'Strawberry Mojito',
      slug: 'strawberry-mojito',
      description: 'Fruity strawberry purée with fresh mint, lime and soda.',
      shortDesc: 'Strawberry purée mint cooler.',
      price: 110,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.7,
      reviewCount: 52,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'mc-6',
      name: 'Mango Mojito',
      slug: 'mango-mojito',
      description: 'Tropical mango pulp muddled with mint, lime and soda.',
      shortDesc: 'Tropical mango mint cooler.',
      price: 110,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.5,
      reviewCount: 22,
      isActive: true,
    },
    {
      id: 'mc-7',
      name: 'Kiwi Mojito',
      slug: 'kiwi-mojito',
      description: 'Tangy kiwi fruit slices muddled with fresh mint, lime and soda.',
      shortDesc: 'Tangy kiwi mint cooler.',
      price: 110,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 19,
      isActive: true,
    },
    {
      id: 'mc-8',
      name: 'Mint Lemonade',
      slug: 'mint-lemonade',
      description: 'Chilled tangy lemonade blended with fresh green mint leaves.',
      shortDesc: 'Tangy lemonade with fresh mint.',
      price: 80,
      stock: 60,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.5,
      reviewCount: 41,
      isActive: true,
    },
    {
      id: 'mc-9',
      name: 'Classic Lemon Mint',
      slug: 'classic-lemon-mint',
      description: 'Traditional sweet and sour lemon drink with fresh mint.',
      shortDesc: 'Traditional sweet and sour lemon.',
      price: 80,
      stock: 60,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.4,
      reviewCount: 29,
      isActive: true,
    },
    {
      id: 'mc-10',
      name: 'Virgin Pina Colada',
      slug: 'virgin-pina-colada',
      description: 'Creamy blend of pineapple juice and coconut cream, served chilled.',
      shortDesc: 'Creamy pineapple and coconut blend.',
      price: 120,
      stock: 40,
      images: ['https://images.unsplash.com/photo-1536935338788-846bb9981813?w=3840&q=100'],
      categoryId: mocktailCat.id,
      rating: 4.8,
      reviewCount: 58,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'mc-11',
      name: 'Peach Iced Tea',
      slug: 'peach-iced-tea',
      description: 'Chilled brewed black tea flavored with sweet peach syrup.',
      shortDesc: 'Sweet peach flavored iced tea.',
      price: 90,
      stock: 60,
      images: ['https://images.unsplash.com/photo-1536935338788-846bb9981813?w=3840&q=100'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 30,
      isActive: true,
    },
    {
      id: 'mc-12',
      name: 'Lemon Iced Tea',
      slug: 'lemon-iced-tea',
      description: 'Classic chilled brewed black tea with lemon squeeze and mint.',
      shortDesc: 'Classic lemon flavored iced tea.',
      price: 90,
      stock: 65,
      images: ['https://images.unsplash.com/photo-1536935338788-846bb9981813?w=3840&q=100'],
      categoryId: mocktailCat.id,
      rating: 4.5,
      reviewCount: 35,
      isActive: true,
    },
    {
      id: 'mc-13',
      name: 'Green Apple Cooler',
      slug: 'green-apple-cooler',
      description: 'Tart green apple juice, cucumber slices and sprite.',
      shortDesc: 'Tart green apple cooler.',
      price: 100,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.5,
      reviewCount: 18,
      isActive: true,
    },
    {
      id: 'mc-14',
      name: 'Blue Ocean',
      slug: 'blue-ocean',
      description: 'Premium blue curaçao with tropical pineapple juice and coconut notes.',
      shortDesc: 'Tropical blue curacao drink.',
      price: 120,
      stock: 40,
      images: ['/blue-lagoon.png'],
      categoryId: mocktailCat.id,
      rating: 4.7,
      reviewCount: 22,
      isActive: true,
    },
    {
      id: 'mc-15',
      name: 'Cranberry Delight',
      slug: 'cranberry-delight',
      description: 'Tart cranberry juice mixed with lime and club soda.',
      shortDesc: 'Tart cranberry lime soda.',
      price: 110,
      stock: 50,
      images: ['/fruit-punch.png'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 26,
      isActive: true,
    },
    {
      id: 'mc-16',
      name: 'Berry Blast',
      slug: 'berry-blast',
      description: 'Fruity mix of blueberry, raspberry, and strawberry syrups with sprite.',
      shortDesc: 'Fruity mixed berry soda.',
      price: 120,
      stock: 45,
      images: ['/fruit-punch.png'],
      categoryId: mocktailCat.id,
      rating: 4.7,
      reviewCount: 40,
      isActive: true,
    },
    {
      id: 'mc-17',
      name: 'Tropical Sunset',
      slug: 'tropical-sunset',
      description: 'Layers of orange juice, pineapple juice, and grenadine syrup.',
      shortDesc: 'Layered orange and pineapple drink.',
      price: 120,
      stock: 40,
      images: ['/fruit-punch.png'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 31,
      isActive: true,
    },
    {
      id: 'mc-18',
      name: 'Fruit Punch',
      slug: 'fruit-punch',
      description: 'Classic mixed fruit juice blend with cream and ice.',
      shortDesc: 'Classic mixed fruit punch.',
      price: 120,
      stock: 55,
      images: ['/fruit-punch.png'],
      categoryId: mocktailCat.id,
      rating: 4.8,
      reviewCount: 65,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      id: 'mc-19',
      name: 'Passion Fruit Mojito',
      slug: 'passion-fruit-mojito',
      description: 'Exotic passion fruit syrup muddled with mint, lime and soda.',
      shortDesc: 'Exotic passion fruit mojito.',
      price: 120,
      stock: 40,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.8,
      reviewCount: 47,
      isActive: true,
    },
    {
      id: 'mc-20',
      name: 'Indori Special Mojito',
      slug: 'indori-special-mojito',
      description: 'Café special secret mix of spices and mint soda.',
      shortDesc: 'Secret spice mint soda mojito.',
      price: 110,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.8,
      reviewCount: 60,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'mc-21',
      name: 'Rainbow Mocktail',
      slug: 'rainbow-mocktail',
      description: 'Stunning 4-layered colorful syrup and juice mocktail.',
      shortDesc: '4-layered colorful syrup drink.',
      price: 140,
      stock: 30,
      images: ['/fruit-punch.png'],
      categoryId: mocktailCat.id,
      rating: 4.9,
      reviewCount: 78,
      isActive: true,
      isFeatured: true,
    },
    {
      id: 'mc-22',
      name: 'Citrus Splash',
      slug: 'citrus-splash',
      description: 'Zesty combination of orange, lemon, lime and club soda.',
      shortDesc: 'Zesty orange lemon lime soda.',
      price: 100,
      stock: 50,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.5,
      reviewCount: 21,
      isActive: true,
    },
    {
      id: 'mc-23',
      name: 'Berry Mojito',
      slug: 'berry-mojito',
      description: 'Mixed berries muddled with mint, lime and club soda.',
      shortDesc: 'Mixed berries mint soda mojito.',
      price: 115,
      stock: 45,
      images: ['/virgin-mojito.png'],
      categoryId: mocktailCat.id,
      rating: 4.7,
      reviewCount: 38,
      isActive: true,
    },
    {
      id: 'mc-24',
      name: 'Watermelon Blast',
      slug: 'watermelon-blast',
      description: 'Ice blended fresh watermelon slushie.',
      shortDesc: 'Ice blended watermelon slushie.',
      price: 110,
      stock: 50,
      images: ['/fruit-punch.png'],
      categoryId: mocktailCat.id,
      rating: 4.6,
      reviewCount: 27,
      isActive: true,
    },
  ];

  console.log('Seeding ' + products.length + ' products...');
  
  for (const prod of products) {
    await prisma.product.upsert({
      where: { id: prod.id },
      update: {
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        shortDesc: prod.shortDesc,
        price: prod.price,
        stock: prod.stock,
        images: prod.images,
        categoryId: prod.categoryId,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        isActive: prod.isActive,
        isFeatured: prod.isFeatured || false,
        isBestseller: prod.isBestseller || false,
      },
      create: {
        id: prod.id,
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        shortDesc: prod.shortDesc,
        price: prod.price,
        stock: prod.stock,
        images: prod.images,
        categoryId: prod.categoryId,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        isActive: prod.isActive,
        isFeatured: prod.isFeatured || false,
        isBestseller: prod.isBestseller || false,
      },
    });
  }

  console.log('Database seeded with complete professional menu successfully! ☕🌱');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
`;

fs.writeFileSync(seedMenuPath, content, 'utf8');
console.log('Generated seed-menu.ts successfully!');
